cc_library(
    name = "sc2_watcher",
    srcs = [
        "sc2_watcher.cpp",
        "sc2_watcher.hpp",
        "sc2_watcher_subscriber.hpp",
    ],
    deps = [
        "@boost//:property_tree",
        "@httplib//:httplib",
    ],
    visibility = [
        "//visibility:public",
    ]
)