cc_library(
  name = "external_service",
  srcs = [
    "externalservice.hpp",
    "externalservice.cpp",
  ],
  deps = [
    "//hydraroach/proto:hydraroach_cpp_proto",
  ],
  visibility = ["//visibility:public"],
)
