cc_binary(
  name = "main",
  srcs = [
    "main.cpp",
  ],
  deps = [
    "//hydraroach/service/external:external",
    "//hydraroach/event:event",
    "//hydraroach/sc2_watcher:sc2_watcher",
    "@boost//:variant",
  ],
)
