cc_library(
  name = "client",
  srcs = [
    "externalclient.hpp",
    "externalclient.cpp",
  ],
  deps = [
    "//hydraroach/proto:hydraroach_cpp_proto",
  ],
  visibility = ["//visibility:public"],
)
