cc_library(
    name = "client",
    srcs = [
        "external_client.cpp",
        "external_client.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hydraroach/proto:hydraroach_cpp_proto",
    ],
)
