cc_binary(
  name = "hydraroach_service",
  srcs = [
    "main.cpp",
    "hydraroachservice.hpp",
    "hydraroachservice.cpp",
  ],
  deps = [
    "//hydraroach/proto:greeter_cpp_proto",
    "//hydraroach/proto:hydraroach_cpp_proto",
  ],
)
