load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cpp_proto_library")

cpp_proto_library(
  name = "hydraroach_cpp_proto",
  protos = ["hydraroach.proto"],
  with_grpc = True,
  visibility = ["//visibility:public"],
)
