cc_library(
  name = "replay_publish",
  srcs = [
    "replaypublisher.hpp",
    "replaypublisher.cpp",
  ],
  deps = [
    "//hydraroach/proto:hydraroach_cpp_proto",
  ],
  visibility = ["//visibility:public"],
)
