git_repository(
  name = "org_pubref_rules_protobuf",
  remote = "https://github.com/pubref/rules_protobuf",
  tag = "v0.8.1",
  #commit = "..." # alternatively, use latest commit on master
)

load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cpp_proto_repositories")
cpp_proto_repositories()

git_repository(
    name = "com_github_nelhage_rules_boost",
    commit = "239ce40e42ab0e3fe7ce84c2e9303ff8a277c41a",
    remote = "https://github.com/nelhage/rules_boost",
)

load("@com_github_nelhage_rules_boost//:boost/boost.bzl", "boost_deps")
boost_deps()

new_git_repository(
    name = "picosha2",
    commit = "77b1e29e94b3a131f202e69d35eafe709ae8e587",
    remote = "https://github.com/okdshin/PicoSHA2.git",
    build_file_content = """
cc_library(
    name = "picosha2",
    srcs = ["picosha2.h"],
    hdrs = ["picosha2.h"],
    visibility = ["//visibility:public"],
    )""",
)